# Generated by Django 2.2.18 on 2021-06-24 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=200, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('order_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('order_email', models.EmailField(max_length=255, unique=True, verbose_name='Электронная почта')),
                ('order_organization_name', models.CharField(max_length=255, verbose_name='Название организации')),
                ('order_organization_address', models.CharField(max_length=255, verbose_name='Адрес организации')),
                ('order_count_images', models.IntegerField(blank=True, verbose_name='Количество план-схем')),
                ('order_date_time', models.DateTimeField(auto_now=True, verbose_name='Дата|время')),
                ('order_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='landing.StatusOrder', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
