# Generated by Django 2.2.18 on 2021-06-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20210628_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusorder',
            name='status_name',
            field=models.CharField(default='Новый', max_length=200, verbose_name='Название статуса'),
        ),
    ]
