# Generated by Django 2.2.18 on 2021-07-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20210713_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_quantity',
            field=models.CharField(max_length=10, verbose_name='Итого'),
        ),
    ]
